### ISSUE TITLE
seq. IDs → alphanumeric hashes; embedding broken

### ISSUE THREAD

**Issue by jm3** [mnuessler/jekyll-asciinema#2]
looks like [Asciinema switched](https://asciinema.org/docs/embedding) to ASCII hashes / chunk IDs instead of sequential numeric IDs, which **jekyll-asciinema** doesn't seem to like:

    % ruby --version
    ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]

    % bundle list | grep ascii
      * jekyll-asciinema (0.2.0)

    ... foo.md:
    {% asciicast 'lMotMSXHCbqpgIxcBse0BOsPU' %}

    ...jekyll: 
    Liquid Exception: Syntax error in tag 'asciicast' while parsing the following markup:
      'lMotMSXHCbqpgIxcBse0BOsPU' Valid syntax: {% asciicast 123456 %} in 
      ~jm3/sites/blog.jm3.net/_posts/2018/10-02-asciinema.md

I tried with and without quotes; let me know if I'm missing something.

FWIW, the actual embed markup to be generated ([linked above](https://asciinema.org/docs/embedding)) is unchanged; the plugin just needs to pass them through like the numeric IDs — i.e., this works:

    <script
      src="https://asciinema.org/a/lMotMSXHCbqpgIxcBse0BOsPU.js"
      id="asciicast-lMotMSXHCbqpgIxcBse0BOsPU" async></script>

**Comment by mnuessler** [comment]
Thanks a lot for taking the time to report the issue!
